server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/duanshipin?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  configuration:
    #mapper配置文件
#    mapper-locations: classpath:mybatis/mapper/*.xml
#    type-aliases-package: com.ljf.duanshipin.domain
#    config-location: classpath:mybatis/mybatis-config.xml
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    开启驼峰
    map-underscore-to-camel-case: true
  redis:
    # Redis数据库索引（默认为 0）
    database: 0
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis 密码
    password:
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 8
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 2000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
    # 连接超时时间（毫秒）
    timeout: 5000